name: okd-release

on:
  workflow_dispatch: {}
jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker images
      env:
        IMAGE_REPOSITORY: ghcr.io/teamziax/noobaa-core
      run: |
        function strip_prefix() {
          local str="$1"
          local prefix="$2"
        
          echo ${str#"$prefix"}
        }
        
        function get_noobaa_version() {
          local version=$(cat package.json | jq -r .version)
          local without_v=$(strip_prefix "$version" v)
        
          echo "v$without_v"
        }
        
        make all
        
        docker tag noobaa ${IMAGE_REPOSITORY}/noobaa-core:$(get_noobaa_version)
        docker push ${IMAGE_REPOSITORY}/noobaa-core:$(get_noobaa_version)
